### ISSUE TITLE
test on a external file

### ISSUE THREAD

**Issue by coincoin73** [vskadandale/multichannel-unet-bss#1]
Hello

Good job!, the results shown in the demo page are impressive.
I want to test the model on an external file (not in the musdb).
I am not an expert so could you provide a simple example of how to call the separation process with a simple wav file ?

Thanks in advance.

**Comment by vskadandale** [comment]
Hi,

Thank you for your interest in our work. To test the model, please follow the following steps:
1) Download the pre-trained weights of the model of your interest from here: https://shorturl.at/aryOX
2) Pre-process your full-length audio sample following the steps in IV. A section of the paper (link to the paper below)
3) After the pre-processing step you will have 256x256 spectrograms, store them as .npy files. You can also follow the steps in  dataset/pre-processing.py for reference. 
4) Download the git repo, configure the paths in settings.py.
5) Run the test/<model of your choice>.py
6) Step 5 results in creation of .wav files of the source-specific estimates for each of the chunks. Now, run eval/stitch_audio.py and this will stitch all the 6s chunks to get the estimates for the full-length audio. 
7) If you would like to find the performance metrics, you can now run eval/eval_metrics.py

For more details, check out our paper here: https://arxiv.org/abs/2003.10414
