### ISSUE TITLE
[WinError 123]  'mnt\\weights\\2021-04-19 17:09:47'

### ISSUE THREAD

**Issue by yangdaowu** [vskadandale/multichannel-unet-bss#2]
Hi, I'm having problems with incorrect file name syntax while doing training
![image](https://user-images.githubusercontent.com/64669901/115211540-3dab3800-a132-11eb-9170-d41e4eccf56d.png)
I am using window system.I think it's the : symbol that appears at the end of the time, but I can't find where to solve the problem.I would like to know how to solve this problem in window system.Thanks!

**Comment by vskadandale** [comment]
Yes, it seems to be a problem with the ':' and the space in the folder name in the Windows OS. 
To work with a simpler filename, you can override the  __setup_experiment__() method in the pytorchframework.py inside every training script. In this method, you can modify the part where it goes `self.workname = str(now)[:19]` as per your interest.

**Comment by yangdaowu** [comment]
Thanks. This problem has been solved.

**Comment by xiongtian-1** [comment]
> Thanks. This problem has been solved.

What have you changed? I also encountered the same problem. thank you
