### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: EXPERIMENTS.ID

### ISSUE THREAD

**Issue by yangdaowu** [vskadandale/multichannel-unet-bss#3]
Hi, I have a new problem in training:
![image](https://user-images.githubusercontent.com/64669901/115375127-11f68380-a200-11eb-98ac-8444abb7839e.png)
Found that it generated such a folder:
![image](https://user-images.githubusercontent.com/64669901/115375098-0a36df00-a200-11eb-96b5-454bfdda31ff.png)
My path setting is like this:
![image](https://user-images.githubusercontent.com/64669901/115375239-2e92bb80-a200-11eb-89f4-5bce300b1510.png)
I can't understand what this problem is. Thank you for your help.

**Comment by yangdaowu** [comment]
Is it a split version problem？

**Comment by yangdaowu** [comment]
Is it a version issue with the splite package

**Comment by vskadandale** [comment]
You have to set a new workname for every experiment. You get this error when you use a previously used workname for another experiment.

**Comment by vskadandale** [comment]
I presume your issue is resolved. Closing this.

**Comment by xiongtian-1** [comment]
> Is it a version issue with the splite package

How did you solve this problem? Thank you very much
